### ISSUE TITLE
Make the "new header" really on all pages.

### ISSUE THREAD

**Issue by moeenio** [MasterOfTheTiger/reimagine-scratch#1] opened 2018-08-17 11:53 UTC
I mean that now, the header looks like the same as the new on all pages, but you could use the same HTML structure as the real new header for all pages, that will make userstyles for the real new header compatible with it.

**Comment by moeenio** [comment] 2018-08-17 11:57
And also, Scratch Team recently changed the header blue.

**Comment by MasterOfTheTiger** [comment] 2018-08-18 02:27
Hmm. Good idea, but I am not sure that it will work as seamless as proposed, but it might work.

One big thing I want to work on is getting refined-scratch's header to work on pages that have Scratch"s new header too. 

Yes, I noticed the color change, but I have not had time to update it.

**Comment by moeenio** [comment] 2019-03-30 11:01
@MasterOfTheTiger Any news ?

**Comment by MasterOfTheTiger** [comment] 2019-03-30 12:07
No. Sorry. I want to be able to do that. But there are some issues with it, and I just moved to a new country and I don't have home Internet yet. So sadly we will have to wait.

**Comment by moeenio** [comment] 2019-03-30 12:10
Ok.

**Comment by VFDan** [comment] 2019-04-14 22:46
@MasterOfTheTiger If you have home internet, can you please change the header blue to the new color?

**Comment by MasterOfTheTiger** [comment] 2019-04-17 15:31
Okay. I have got it now. I will do that soon.

**Comment by MasterOfTheTiger** [comment] 2019-04-17 16:05
@VFDan Fixed in 13206cf73a45b6a379c1b8d123a7d2a6e6394d6b

**Comment by VFDan** [comment] 2019-08-05 20:15
@MasterOfTheTiger Can you please ship it?

**Comment by MasterOfTheTiger** [comment] 2019-08-06 08:03
@VFDan Submitted to AMO.

**Comment by moeenio** [comment] 2019-08-06 09:20
Fun thing, I'm using the [old-scratch-blue](https://github.com/csourcesc/old-scratch-blue) userstyle, and on the "new header" of the extension, nothing is in the userstyle's color (normal), except...
![Capture d’écran 2019-08-06 à 11 20 19](https://user-images.githubusercontent.com/37651007/62527851-364bda00-b83c-11e9-8c0c-3616452f8259.png)
the user dropdown 🤔

**Comment by VFDan** [comment] 2019-08-06 15:16
It doesn't seem to have changed, at least in the Discussion Forums
![image](https://user-images.githubusercontent.com/44413950/62552441-a312a480-b83b-11e9-863d-ad6eac448d79.png)

**Comment by MasterOfTheTiger** [comment] 2019-08-06 17:30
@VFDan, I cannot reproduce. Please do the following:
- Make sure you are using Reimagined Scratch v0.1.3
- Take a screenshot of the affected page
- Post the link of the affected page

**Comment by moeenio** [comment] 2019-08-07 09:23
You mean reimagined scratch ? x)

**Comment by moeenio** [comment] 2019-08-07 09:25
@VFDan Make sure you update your extension

**Comment by VFDan** [comment] 2019-08-07 15:52
Ah yes. I forgot to update.

**Comment by moeenio** [comment] 2019-08-08 10:19
That's fine.

**Closed as completed** 2021-11-03 13:32 UTC
